title: "_CODE Sky"
author: "YoungGong"

remote_theme: "kitian616/jekyll-TeXt-theme"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

exclude:
  - 템플릿/

# TeXt 테마 전용 옵션
text_skin: "ocean"          # default / night / forest / ocean / paper
highlight: "github"         # default / github / tomorrow / tomorrow-night / zenburn .

# 폰트 설정
text_font: "Noto Sans KR"   # 구글폰트 예시

# Load SCSS (없어도 자동탐지 하기는 함)
sass:
  style: compressed